
services:
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - postgres_service
      - redis
    environment:
      POSTGRES_NAME: crm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_HOST: postgres_service
      POSTGRES_PORT: 5432

  postgres_service:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: crm_postgres_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always

  celery:
    build: .
    command: celery -A config worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - postgres_service

  beat:
    build: .
    command: celery -A config beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres_service

volumes:
  postgres_data: